spring:
  application:
    name: soft

  #BASE DE DATOS
  datasource:
    url: jdbc:postgresql://localhost:5432/audrey
    username: santer
    password: "1234"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  # Liquibase gestiona el esquema
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

#SEGURIDAD
audrey:
  design-engine:
    url: http://localhost:8081
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token-expiration: 3600000   # 1 hora
      refresh-token-expiration: 604800000 # 7 días

logging:
  level:
    liquibase: INFO