spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

audrey:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
      refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
  level:
    root: WARN
    com.audrey: INFO
    liquibase: INFO
